server:
  port: 8082
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: client
  devtools:
    livereload:
      port: 35730
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.197:3306/test?serverTimezone=UTC
      username: root
      password: root
      initial-size: 5
      min-idle: 1
      validation-query: select 1
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8081/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: '*'

logging:
  level:
    root: info
    com.example: debug
  file:
    name: app/${spring.application.name}.log