server:
  port: 8082
  servlet:
    context-path: /client
spring:
  devtools:
    livereload:
      port: 35730
  application:
    name: client
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.197:3306/test?serverTimezone=UTC
      username: root
      password: root
      initial-size: 5
      min-idle: 1
      validation-query: select 1
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8081/eureka/
logging:
  level:
    root: info
    com.example: debug
  file:
    name: app/client.log
foo: fooclient