
spring:
  boot:
    admin:
      client:
        url: http://192.168.0.197:8081/monitor
  cloud:
    config:
      uri: http://192.168.0.197:8082
      discovery:
        enabled: false
  zipkin:
    base-url: http://192.168.0.197:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.197:8081/eureka/

foo: fooconfig-local-v13
