server:
  port: 8084
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: config
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: ${spring.application.name}
      profile: local
  rabbitmq:
    addresses: localhost:5672
    username: rabbit
    password: rabbit
#      uri: http://localhost:8086
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8081/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude:
          - "env"
          - "beans"

logging:
  level:
    root: info
    com.example: debug
  file:
    name: app/${spring.application.name}.log

foo: fooconfig