server:
  port: 8084
  servlet:
    context-path: /config
spring:
  application:
    name: config
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: config
      profile: local
#      uri: http://localhost:8086
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8081/eureka/
logging:
  level:
    root: info
    com.example: debug
  file:
    name: app/config.log
feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /
foo: fooconfig