server:
  port: 8084
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: config
  boot:
    admin:
      client:
        url: http://${eureka.eureka-hostname}:${eureka.eureka-port}/monitor
        auto-deregistration: true
        instance:
          prefer-ip: true
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
  zipkin:
    base-url: http://zipkin-server:8087
eureka:
  eureka-hostname: eureka-server
  eureka-port: 8081
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.eureka-hostname}:${eureka.eureka-port}/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude:
          - "env"
          - "beans"

logging:
  level:
    root: info
    com.example: debug
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: warn
  file:
    name: app/${spring.application.name}.log

foo: fooconfig