eureka:
  eureka-hostname: localhost
  eureka-port: 8081
  zipkin-port: 8087
spring:
  cloud:
    config:
      discovery:
        enabled: false
      uri: http://localhost:9006
  zipkin:
    base-url: http://${eureka.eureka-hostname}:${eureka.zipkin-port}
foo: fooconfig-local-v8
